version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    main: ./cmd/mockoho/main.go

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: zip

release:
  github:
    owner: kohofinancial
    name: mockoho

brews:
  - name: mockoho
    homepage: "https://github.com/kohofinancial/mockoho"
    description: "Mock server system for frontend development"
    license: "MIT"
    repository:
      owner: kohofinancial
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "mockoho"
    test: |
      system "#{bin}/mockoho --version"
    dependencies:
      - name: go
        type: optional
